
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar-plugin.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
- light:
  - unique_id: bedroom_custom_dimmer
    name: Bedroom Dimmer
    default_entity_id: light.bedroom_dimmer

    level: '{{ ((states(''number.bedroom_dimmer_fan_bright_value'') | float) / 1000
      * 255) | int }}'
    state: '{{ is_state(''switch.bedroom_dimmer_fan_light'', ''on'') }}'

    turn_on:
      action: switch.turn_on
      target:
        entity_id: switch.bedroom_dimmer_fan_light

    turn_off:
      action: switch.turn_off
      target:
        entity_id: switch.bedroom_dimmer_fan_light
      
    set_level:
      action: script.bedroom_light_level
      data:
        brightness: '{{brightness}}'

- button:
  - unique_id: cat_litter_manual_clean
    name: Clean Cat Litter
    press:
      action: button.press
      target:
        entity_id: button.cat_litter_manual_clean

- fan:
  - unique_id: bedroom_custom_fan
    name: Bedroom Fan
    speed_count: 4
    state: '{{ is_state(''switch.bedroom_dimmer_fan_switch_fan'', ''on'') }}'
    percentage: '{{ state_attr(''fan.bedroom_overhead_switches'', ''percentage'') | int(0) }}'
    turn_on:
      action: switch.turn_on
      target:
        entity_id: switch.bedroom_dimmer_fan_switch_fan
    turn_off:
      action: switch.turn_off
      target:
        entity_id: switch.bedroom_dimmer_fan_switch_fan
    set_percentage:
      action: script.bedroom_fan_speed
      data:
        percentage: '{{percentage}}'

- binary_sensor:
  - unique_id: cat_litter_anti_pinch
    name: "Cat Litter Anti-Pinch"
    device_class: problem
    state: "{{ is_state('select.cat_litter_relay_status', '2') }}"
    icon: >
      {% if is_state('select.cat_litter_relay_status', '2') %}
        mdi:alert-circle
      {% else %}
        mdi:check-circle
      {% endif %}
  - unique_id: cat_litter_anti_pinch_door
    name: "Cat Litter Box Drawer Sensor"
    device_class: door
    state: "{{ is_state('select.cat_litter_relay_status', '2') }}"
    icon: >
      {% if is_state('select.cat_litter_relay_status', '2') %}
        mdi:door-open
      {% else %}
        mdi:door-closed
      {% endif %}

input_boolean:
  bedroom_sunrise_start:
    name: Bedroom Sunrise Start
    icon: mdi:weather-sunny-alert

input_number:
  bedroom_sunrise_expected_brightness:
    name: Bedroom Sunrise Expected Brightness
    min: 0
    max: 1000
    step: 1
